stages:
  - build


build:
  image: azul/zulu-openjdk:17-latest
  only: Back
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - backend/build/libs/*.jar
    expire_in: 1 week
  tags:
    - back
