services:
  webapp:
    build:									#image를 DockerFile 기반으로 사용한다
      context: .							#DockerFile이 있는 디렉토리
      dockerfile: Dockerfile				#기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
    container_name: pubble
    restart: always
    depends_on:
      - pubble_mysql
    ports:
      - "10425:9091"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}

  pubble_mysql:
    image: mysql:latest
    container_name: pubble_mysql
    volumes:
      - ./docker-compose/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # 여기에 DB_PASSWORD를 사용해 MYSQL_ROOT_PASSWORD 설정
      MYSQL_DATABASE: pubble               # 옵션으로 데이터베이스를 지정할 수 있습니다
