server:
  port: 9091

spring:
  application:
    name: pubble

  datasource:
    url: ENC(rWYclDMbGAznbF3MQ0DFsrHDHKaaiIYG4HYCl7M81YxK1SXW1nkwc7qEN1pGRh02)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(mCoXDUfo7pgBQiB1UgTEsQ==)
    password: ENC(ebSdgNbER/IlSSpsoLo0LjXXgGjBobLw)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

springdoc:
  swagger-ui:
    path: /v3/api-docs